apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa # 규약에 명시된 이름 강제
  namespace: hailcast
  annotations:
   eks.amazonaws.com/role-arn: "arn:aws:iam::797452357900:role/hailcast-dev-irsa-worker"
