apiVersion: v1
kind: Service
metadata:
  name: hailcast-weather-cron
  namespace: hailcast
spec:
  selector:
    app: hailcast-weather-cron
  ports:
    - port: 8002
      targetPort: 8002
      name: http