apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: call-api
  namespace: hailcast
spec:
  selector:
    matchLabels:
      app: hailcast-call-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
