apiVersion: v1
kind: Service
metadata:
  name: hailcast-call-api
  namespace: hailcast
  labels:
    app: hailcast-call-api
spec:
  selector:
    app: hailcast-call-api
  ports:
    - port: 8000
      targetPort: 8000