apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predict
  namespace: hailcast
spec:
  selector:
    matchLabels:
      app: predict
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
