apiVersion: v1
kind: ServiceAccount
metadata:
  name: predict-sa # 🌟 필수 규칙: IRSA 권한을 받기 위한 정확한 SA 이름
  namespace: hailcast
  annotations:
    # 인프라팀이 추후 생성할 IAM Role의 ARN이 들어갈 자리입니다.
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/hailcast-dev-irsa-predict"