apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.20.1
      helm:
        releaseName: keda
        valueFiles:
          - $values/addons/keda/values.yaml

    - repoURL: https://github.com/ThisPod-ThatPod/project3-hailcast-manifests.git
      targetRevision: dev
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
