apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://opencost.github.io/opencost-helm-chart
      chart: opencost
      targetRevision: 2.5.27
      helm:
        releaseName: opencost
        valueFiles:
          - $values/addons/opencost/values.yaml
    - repoURL: https://github.com/ThisPod-ThatPod/project3-hailcast-manifests.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
