apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ThisPod-ThatPod/project3-hailcast-manifests.git'
    targetRevision: main
    path: apps/worker
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hailcast
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # ⑨ Predict와 동일하게 네임스페이스 생성 옵션 추가